### ISSUE TITLE
Helper Message Markdown Not Rendering

### ISSUE THREAD

**Issue by samad-yar-khan** [RocketChat/Apps.Github22#65]
### Description:

Whenever someone enters the command `/gh help`, the helper message shows up in backticks but the message is not properly rendered inside a markdown block. The message is displayed as plain text.

### Steps to reproduce:

1. Enter `/gh help` in the input message box 
2. Helper Message shows up in plain text.

### Expected behavior:

- Helper message should  be displayed in markdown format as a block of text.

### Actual behavior:
- We get plain text
 - 
![image](https://user-images.githubusercontent.com/70485812/224835382-d08972f3-212c-4225-b6b1-ad6ccb09f941.png)

**Comment by Nabhag8848** [comment]
Hey @samad-yar-khan can we avoid that markdown block by any chance? 
## why i think we should avoid having markdown block:
- When using markdown block we won't able to highlight the command and if we think from user perpective most of us with time would avoid reading the text and main thing user will look at is command and try it so  here main source of info is that command which should stand out from the text instead of whole text being standing out which would make a little bad user feeling. 

## What we can have: 
- Instead we can have each of these commands as point. why? No user would care about how many command are there so if we think from user perspective we can avoid having those number points and have dot points instead like the following i did in the oauth app.
![Screenshot from 2023-03-21 01-21-33](https://user-images.githubusercontent.com/65061890/226451046-723491fe-812c-4b42-8f04-fa8470394da5.png)

# further thoughts: 
- I had an idea of having those points as attachments and tried but for some reason those attachments are not extending to whole room width area causing the each point to extend to two lines and that looks bad.
